const express=require('express');
const router=express.Router();
var bodyParser = require('body-parser');
var jsonParser = bodyParser.json();
const customerController=require('../controllers/customerController');
router.use('/product',require('./productRoutes'));
router.use('/order',require('./orderRoutes'));
router.post('/createCustomer',jsonParser,customerController.createCustomer);
router.get('/fetchCustomer',jsonParser,customerController.fetchCustomer);
router.get('/fetchSpecificCustomerOrderList/:customerId',customerController.fetchSpecificCustomerOrderList);
module.exports=router;